name: Build and Release
on:
  workflow_dispatch: # 允许手动触发
  
jobs:
  build:
    runs-on: ubuntu-latest
    container: alpine:latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Build Essentials
        run: apk add --no-cache go musl-dev gcc sqlite-dev build-base
      - name: Build Binary
        run: |
          export CGO_ENABLED=1
          export GOOS=linux
          go mod tidy
          go build -ldflags '-linkmode external -extldflags "-static" -s -w' -o chatroom main.go
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: chatroom-binary
          path: chatroom
